read only mode, and larger terminal

diff --git a/hed b/hed
--- a/hed
+++ b/hed
@@ -9,18 +9,21 @@ set -u #unset variables are errors
 typeset -A changes           # pending writes to file.  changes[offset]=ascii-value
 typeset -a asc_to_print      # printable character translation. asc_to_print[ascii_value]=character
 typeset -A -i ch_to_ascval   # byte to ascii value. ch_to_ascval[byte]=ascii-value, byte is typeset -b (base64), from read -r -N1
-typeset lrl                  # logical record length
+typeset lrl=256              # logical record length, default
+typeset dump_per_line=16     # default is 16 bytes per line on dump
+typeset readonly=""          # if set, then read only mode enabled
 
 # terminal codes
 typeset smso="$(tput smso)"  # set standout mode
 typeset rmso="$(tput rmso)"  # rm standout mode
 typeset smul="$(tput smul)"  # set underline
 typeset rmul="$(tput rmul)"  # rm underline
+typeset cols="$(tput cols)"  # number of columns on screen
 
 usage()
 {
     echo >&2 "Hex editor"
-    echo >&2 "usage: hed <file> [record length, default 256]"
+    echo >&2 "usage: hed [-r (read only)] <file> [record length]"
     exit 1
 }
 
@@ -29,7 +32,7 @@ function display_status_line
     # display status line
     typeset eof=$(3<#((EOF)))
     typeset maxrec=$((int(eof/lrl)))
-    printf "$FILE  eof %d (%#x)  lrl $lrl  max rec $maxrec [h for help]\n" $eof $eof
+    printf "$FILE  $readonly  eof %d (%#x)  lrl $lrl  max rec $maxrec [h for help]\n" $eof $eof
     typeset i
     for i in ${!changes[*]};do
         typeset -i16 ascval=${changes[$i]}
@@ -76,13 +79,13 @@ function dump
 
     update_position offset eof           # check offset in range, and get eof
 
-    typeset low=$((offset - offset%16))  #can fit 16 bytes per row.
+    typeset low=$((offset - offset%dump_per_line))  #can fit n bytes per row.
     typeset dumphigh=$((offset+nrecs*lrl))
     if ((dumphigh>eof));then
         dumphigh=$eof
     fi
-    typeset high=$((ceil(1.0*dumphigh/16)*16))
-    # starts at increments of 16 low and high
+    typeset high=$((ceil(1.0*dumphigh/dump_per_line)*dump_per_line))
+    # starts at increments of dump_per_line low and high
     # bytes inside requested offset are shown
     # bytes outside range are replaced with .. or " "
 
@@ -90,14 +93,21 @@ function dump
 
     3<#((offset))               # set read pos of file
 
-    printf "$smul %10s   0 1  2 3  4 5  6 7   8 9  a b  c d  e f$rmul\n" ' '
+    printf "$smul              "
+    for (( i=0; i<dump_per_line; i++ ));do
+        printf "%2x" $i
+        (( (i%8)==7 )) && printf " "
+        (( (i%2)==1 )) && printf " "
+    done
+#    printf "$smul               0 1  2 3  4 5  6 7   8 9  a b  c d  e f$rmul\n"
+    printf "$rmul\n"
     # dump each line
-    for (( i=low; i<high; i+=16 ));do
+    for (( i=low; i<high; i+=dump_per_line ));do
 
         printf " %#10x: " $i 
         typeset line=""
-        for (( j=i; j<i+16; j++ ));do
-            if (( j==i+8 )); then
+        for (( j=i; j<i+dump_per_line; j++ ));do
+            if (( j%8 == 0 )); then
                 printf " " # extra space in hex dump to separate 8 byte segments
             fi
             if (( j>=eof )); then
@@ -283,6 +293,10 @@ EOF
 
 function main
 {
+    if [[ $1 = -r ]];then
+        shift
+        readonly="read-only"
+    fi
     # Find file to open
     if [[ -z ${1:-} ]]; then
         usage
@@ -290,18 +304,23 @@ function main
     fi
     FILE="$1"
     if [[ ! -f $FILE ]]; then
-        echo >&2 "file not found $FILE"
+        echo >&2 "cannot open '$FILE'"
         exit 1
     fi
+    lrl=${2:-$lrl} # lrl is set to default based on terminal size. override if requested
 
-    # logical record length, default to 256
-
-    lrl=${2:-256}
-    if (( lrl>32768 || lrl<1 )); then
-        lrl=256
+    if [[ -z $readonly ]]; then
+        exec 3<>$FILE  # open for read-write
+    else
+        exec 3<$FILE   # open for reads only
     fi
 
-    exec 3<>$FILE
+    # adjust output for larger terminal.
+    if (( cols >= 132 )); then
+        # larger terminal, show more.
+        dump_per_line=32
+        lrl=1024
+    fi
 
     # set up byte-to-ascii and ascii-to-printable arrays
     # byte is base 64 from 'read -r' to a binary typeset var
@@ -442,6 +461,12 @@ function main
             #    @(*)          \4 rest of line
             typeset editpos="${.sh.match[2]}"
             typeset patches="${.sh.match[4]}"
+
+            if [[ -n $readonly ]]; then
+                echo "read only mode. edit not permitted"
+                continue
+            fi
+
             typeset offset=-1
             readnum offset $editpos
             if ((offset==-1)); then
@@ -469,6 +494,10 @@ function main
 
         elif [[ $cmd = w ]]; then
 
+            if [[ -n $readonly ]]; then
+                echo "read only mode. edit not permitted"
+                continue
+            fi
             if (( ${#changes[*]}==0 )); then
                 echo "no changes pending."
                 continue
